{% set version = "0.23.1" %}

package:
  name: xh
  version: {{ version }}

source:
  url: https://github.com/ducaale/xh/archive/v{{ version }}.tar.gz
  sha256: 3f7dc6a3c8809f57a32c9aae7a192b54e87702a65d426784c1775676eea2e67f

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - xh --help

about:
  home: https://github.com/ducaale/xh
  dev_url: https://github.com/ducaale/xh
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Friendly and fast tool for sending HTTP requests

extra:
  recipe-maintainers:
    - apcamargo