{% set name = "phylopath" %}

package:
  name: r-{{ name }}
  version: '{{ version }}'

source:
  url: https://cran.r-project.org/src/contrib/phylopath_{{ version }}.tar.gz
  sha256: 9e0f907f1f6b26b01d04d3702dbefc48f8648322de2cfbbc050d89d84b5929a9

build:
  number: 0
  merge_build_host: true
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-ape >=4.1
    - r-base
    - r-future.apply
    - r-ggm >=2.3
    - r-ggplot2 >=3.0.0
    - r-ggraph >=1.0.0
    - r-igraph >=1.0.1
    - r-phylolm >=2.5
    - r-purrr >=0.2.3
    - r-tibble
  run:
    - r-ape >=4.1
    - r-base
    - r-future.apply
    - r-ggm >=2.3
    - r-ggplot2 >=3.0.0
    - r-ggraph >=1.0.0
    - r-igraph >=1.0.1
    - r-phylolm >=2.5
    - r-purrr >=0.2.3
    - r-tibble

test:
  commands:
    - $R -e "library('phylopath')"  # [not win]
    - "\"%R%\" -e \"library('phylopath')\""  # [win]

about:
  home: https://Ax3man.github.io/phylopath/
  summary: >
    A comprehensive and easy to use R implementation of confirmatory phylogenetic
    path analysis as described by Von Hardenberg and Gonzalez-Voyer (2012)
    <doi:10.1111/j.1558-5646.2012.01790.x>.
  license: GPL-3.0-or-later

extra:
  recipe-maintainers:
    - apcamargo
