{% set name = "shell-gpt" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/shell_gpt-{{ version }}.tar.gz
  sha256: 3384af581ba95b6d6da7004e1ede5be0884fe4a72783b408dca3c0ac3fff71e9

build:
  skip: true  # [py<37]
  entry_points:
    - sgpt = sgpt:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - openai >=1.34.0,<2.0.0
    - typer >=0.7.0,<1.0.0
    - click >=7.1.1,<9.0.0
    - rich >=13.1.0,<14.0.0
    - distro >=1.8.0,<2.0.0
    - instructor >=0.4.5,<1.0.0
    - pyreadline3 >=3.4.1,<4.0.0  # [win]

about:
  home: https://github.com/TheR1D/shell_gpt
  summary: >-
    A command-line productivity tool powered by large language models, 
    will help you accomplish your tasks faster and more efficiently.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apcamargo
