context:
  version: "0.2.1"

package:
  name: crush
  version: ${{ version }}

source:
  - url: https://github.com/charmbracelet/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: c1f24b8334abc114f0ff4f08a59fa50a52972cd18c23b7eddd1eaa4b044ea390

build:
  number: 0
  script:
    - if: unix
      then:
        - cd $SRC_DIR
        - go build -o $PREFIX/bin/spf
        - go-licenses save $SRC_DIR --save_path=$RECIPE_DIR/license-files
    - if: win
      then:
        - go build -o %PREFIX%/spf.exe
        - go-licenses save %SRC_DIR% --save_path=%RECIPE_DIR%/license-files

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - crush --help

about:
  homepage: https://github.com/charmbracelet/crush
  repository: https://github.com/charmbracelet/crush
  documentation: https://github.com/charmbracelet/crush
  summary: The glamourous AI coding agent for your favourite terminal
  description: |
    Crush is a terminal-based coding assistant that integrates your tools, code,
    and workflows with the LLM of your choice. It supports multiple models,
    including custom ones via OpenAI- or Anthropic-compatible APIs, and allows
    switching models mid-session while preserving context. Users can maintain
    multiple sessions per project, benefit from LSP-based contextual enhancements,
    and extend functionality through MCPs (http, stdio, and sse). Crush offers
    first-class support across macOS, Linux, Windows (PowerShell and WSL),
    FreeBSD, OpenBSD, and NetBSD.
  license: FSL-1.1-MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - apcamargo
