{% set name = "packcircles" %}
{% set version = "0.3.7" %}
{% set posix = "m2-" if win else "" %}
{% set native = "m2w64-" if win else "" %}

package:
  name: r-{{ name }}
  version: '{{ version }}'

source:
  url: https://cran.r-project.org/src/contrib/packcircles_{{ version }}.tar.gz
  sha256: cdc05becce2973b23da7be9684df5d23f4aa5a664f2d724d3379bcaf779de39f

build:
  number: 0
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - autoconf                     # [unix]
    - {{ compiler("c") }}          # [unix]
    - {{ stdlib("c") }}            # [unix]
    - {{ compiler("m2w64_c") }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler("cxx") }}        # [unix]
    - {{ compiler("m2w64_cxx") }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make              # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-rcpp >=1.0.0
    - r-base
    - r-checkmate
  run:
    - r-rcpp >=1.0.0
    - r-base
    - r-checkmate

test:
  commands:
    - $R -e "library('packcircles')"  # [not win]
    - "\"%R%\" -e \"library('packcircles')\""  # [win]

about:
  home: https://github.com/mbedward/packcircles
  summary: Algorithms to find arrangements of non-overlapping circles.
  license: MIT
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo
