{% set version = "1.1.0" %}

package:
  name: hevi
  version: {{ version }}

source:
  url: https://github.com/Arnau478/hevi/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d1c444301c65910b171541f1e3d1445cc3ff003dfc8218b976982f80bccd9ee0

build:
  number: 0

requirements:
  build:
    - zig

test:
  commands:
    - hevi --help

about:
  home: https://arnau478.github.io/hevi/
  dev_url: https://github.com/Arnau478/hevi
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: A hex viewer

extra:
  recipe-maintainers:
    - apcamargo
